### PR TITLE
Use got instead of request

### PR DESCRIPTION
**Pull request by kaatt**
* it's going to auto-retry all network errors 2 times which will make this library more stable
* lesser lines of code

bluebird.resolve is necessary only to make the promise returned by got a bluebird-promise 

if `this.version().bind(this).done` can be replaced with `this.version().then`, then we can remove bluebird too.

`package-lock.json` will need to be updated using NPM

### CODE REVIEW

**Comment by robertklep** [comment]
Thanks!

As it happens, I've been working on a rewrite (https://github.com/robertklep/node-sabnzbd/tree/rewrite) which drops `request` in favor of `node-fetch`, and also drops Bluebird as a dependency.

It's not entirely finished yet, and perhaps `got` is a good alternative for `node-fetch` (although I've never had stability issues, the option to automatically retry sounds interesting), so feel free to check it out and see if it better suits you.

To install that particular branch:
```
$ npm i robertklep/node-sabnzbd#rewrite
```

Caveat: I haven't yet used the rewrite branch in actual projects, so I'm not sure it it'll work. It should be backward compatible in terms of the data it returns.

**Comment by kaatt** [comment]
a ES2015 version is pretty good. you can use Object.assign to compress the cmd function there. 

i encounter multiple ECONNRESET errors without adding network retry logic. so i suppose you should add some form of retry logic to the cmd function. i'd simply use got instead of using node-fetch and adding retry logic: https://npmcompare.com/compare/got,node-fetch

**Comment by robertklep** [comment]
`got` looks good, I'll replace `node-fetch` with it.

**Comment by robertklep** [comment]
I just published `sabnzbd@2.0.0`, which uses `got`. I've been using it in my own projects for a few weeks now, and it seems to work just fine. Thanks again!

**Pull request closed without merging**
